#pragma once

#define DWMAJORVERSION 1
#define DWMINORRVERSION 0
#define DWBUILDVERSION 166
#define DWPATCHVERSION 0

//Copy next lines in .rc files
//FILEVERSION DWMAJORVERSION,DWMINORRVERSION,DWBUILDVERSION,DWPATCHVERSION
//PRODUCTVERSION DWMAJORVERSION,DWMINORRVERSION,DWBUILDVERSION,DWPATCHVERSION
